//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Messages.User {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageUserErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageUserErrors() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Application.Messages.User.MessageUserErrors", typeof(MessageUserErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Usuario se ha creado exitosamente.
        /// </summary>
        internal static string CreatedUser {
            get {
                return ResourceManager.GetString("CreatedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al crear el usuario.
        /// </summary>
        internal static string CreateUserError {
            get {
                return ResourceManager.GetString("CreateUserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha de nacimiento es requerida.
        /// </summary>
        internal static string DateOfBirthRequeared {
            get {
                return ResourceManager.GetString("DateOfBirthRequeared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El numer de documento de identificación es requerido.
        /// </summary>
        internal static string DocumentRequared {
            get {
                return ResourceManager.GetString("DocumentRequared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El tipo de documento es requerido.
        /// </summary>
        internal static string DocumentTypeIdRequared {
            get {
                return ResourceManager.GetString("DocumentTypeIdRequared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo es requerido.
        /// </summary>
        internal static string EmailRequared {
            get {
                return ResourceManager.GetString("EmailRequared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al cargar la imagen.
        /// </summary>
        internal static string ErrorUploadImage {
            get {
                return ResourceManager.GetString("ErrorUploadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La imagen es requerida.
        /// </summary>
        internal static string ImageRequared {
            get {
                return ResourceManager.GetString("ImageRequared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Contraseña o el Usuario son incorrectos.
        /// </summary>
        internal static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El primer apellido es requerido.
        /// </summary>
        internal static string LastNameRequared {
            get {
                return ResourceManager.GetString("LastNameRequared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre es requerido.
        /// </summary>
        internal static string NameRequared {
            get {
                return ResourceManager.GetString("NameRequared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se proporciono ningun token de auntorizacion.
        /// </summary>
        internal static string NotToken {
            get {
                return ResourceManager.GetString("NotToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El numero de telefono debe ser de 10 caracteres.
        /// </summary>
        internal static string NumberPhoneLength {
            get {
                return ResourceManager.GetString("NumberPhoneLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El numero de telefono es requerido.
        /// </summary>
        internal static string NumberPhoneRequared {
            get {
                return ResourceManager.GetString("NumberPhoneRequared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña es requerida.
        /// </summary>
        internal static string PasswordRequared {
            get {
                return ResourceManager.GetString("PasswordRequared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña es requerida.
        /// </summary>
        internal static string PasswordRequareRolIdRequared {
            get {
                return ResourceManager.GetString("PasswordRequareRolIdRequared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El rol debe ser mayor a 0.
        /// </summary>
        internal static string RolIdCero {
            get {
                return ResourceManager.GetString("RolIdCero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El rol es requerido.
        /// </summary>
        internal static string RolIdRequared {
            get {
                return ResourceManager.GetString("RolIdRequared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Token de autorizacion.
        /// </summary>
        internal static string TokenAuthorization {
            get {
                return ResourceManager.GetString("TokenAuthorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Usuario ya esta registrado.
        /// </summary>
        internal static string UserExist {
            get {
                return ResourceManager.GetString("UserExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario no esta registrado.
        /// </summary>
        internal static string UserNotRegistered {
            get {
                return ResourceManager.GetString("UserNotRegistered", resourceCulture);
            }
        }
    }
}
